require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'base_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'Firebase/Analytics'

  target 'base_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'base_app-tvOS' do
  # Pods for base_app-tvOS

  target 'base_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
